/*??
 * COPYRIGHT (C) 2012 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE,
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the
 * License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/


package com.zotoh.bedrock.device

import java.io.File
import com.zotoh.fwk.util.StrUte._

/**
 * An Event generated by the FilePicker device.  This event carries the
 * reference to the file which has been picked up by the device.
 *
 * @author kenl
 */
class FileEvent(dev:Device,private var _file:File ) extends Event(dev) {

  private val serialVersionUID = 4218879282887901571L
  private var _origPath:String=""
  @transient private var _error:Option[Exception]=None

  /**
   * @param dev
   * @param originalFile
   * @param f
   * @param e
   */
  def this(dev:Device, originalFile:String, f:File, e:Option[Exception]) {
    this(dev,f)
    _error=e
    _origPath=nsb(originalFile)
  }

  /**
   * @return
   */
  def origFilePath() = _origPath

  /**
   * @return
   */
  def file() = _file

  /**
   * @return
   */
  def hasError() = _error == None

  /**
   * @return
   */
  def errorObj() = _error

}

