/*??
 * COPYRIGHT (C) 2012 CHERIMOIA LLC. ALL RIGHTS RESERVED.
 *
 * THIS IS FREE SOFTWARE; YOU CAN REDISTRIBUTE IT AND/OR
 * MODIFY IT UNDER THE TERMS OF THE APACHE LICENSE,
 * VERSION 2.0 (THE "LICENSE").
 *
 * THIS LIBRARY IS DISTRIBUTED IN THE HOPE THAT IT WILL BE USEFUL,
 * BUT WITHOUT ANY WARRANTY; WITHOUT EVEN THE IMPLIED WARRANTY OF
 * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE.
 *
 * SEE THE LICENSE FOR THE SPECIFIC LANGUAGE GOVERNING PERMISSIONS
 * AND LIMITATIONS UNDER THE LICENSE.
 *
 * You should have received a copy of the Apache License
 * along with this distribution; if not, you may obtain a copy of the
 * License at
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 ??*/

package com.zotoh.bedrock.device.netty

import java.io.IOException

import org.jboss.netty.buffer.ChannelBuffer
import org.jboss.netty.buffer.ChannelBufferInputStream
import org.jboss.netty.handler.codec.http.websocketx.WebSocketFrame

import com.zotoh.fwk.util.StrUte._
import com.zotoh.bedrock.device.Device
import com.zotoh.bedrock.device.Event

/**
 * Events generated by a WebSocket device.
 *
 * @author kenl
 */
class WebSockEvent( private val _data:Any, dev:Device) extends Event(dev) {

  private val serialVersionUID = 8224375822172669671L

  /**
   * @return
   */
  def data() =  Some(_data)

  /**
   * @return
   */
  def isBinary() = {
    _data match {
      case x:Array[Byte] => true
      case _ => false
    }
  }

  /**
   * @return
   */
  def isText() = ! isBinary()

  /**
   * @return
   */
  def text() = {
    _data match {
      case x:String => x
      case _ => ""
    }
  }

  /**
   * @return
   */
  def binData() = {
    _data match {
      case x:Array[Byte] => x
      case _ => null
    }
  }




}
